######################################################################
# Automatically generated by qmake (3.0) Wed Aug 21 00:06:57 2013
######################################################################

TEMPLATE = app
TARGET = Tikbew
INCLUDEPATH += /usr/include/qt5/QtWidgets/
QT += core gui widgets webkit webkitwidgets
#LIBS += 

# Input
HEADERS += MainWindow.h

SOURCES += Browser.cpp MainWindow.cpp
